### ISSUE TITLE
Switches acting wrong in HA

### ISSUE THREAD

**Issue by fsedarkalex** [ReneNulschDE/ha_link2home#7]
This time it is actually an issue and not my own stupidness 😆 

I am switching one socket on via HA. The socket actually switches on near-instantly as expeced.
The State in HA however goes to "off" again after a second of two.

Also last operation stays at its value. I waited a few minutes but the switch never shows the "on" state (yet)

using 0.1.0

![image](https://github.com/user-attachments/assets/2ce54f41-3055-43e1-8eeb-f13d69c69e6d)

**Comment by ReneNulschDE** [comment]
Hi, could you enable the debug log? I expect that the socket is on right?

the process is the following, when you use the switch , a network package is send to the socket. The socket answers with a package, yes I’m on. Looks like we miss the answer package. This could happen as this is just a casting protocol.  Let me check with your debug log…

last operation is a cloud value and not trustful. Sometimes the Chinese cloud has an updated value and most often not.

**Comment by fsedarkalex** [comment]
```
2024-07-29 15:35:05.900 DEBUG (MainThread) [custom_components.ha_link2home.coordinator] set_state: IP: 192.168.181.119, data: a104e8fdf8052cce0009001102D271500101FF
2024-07-29 15:35:05.900 INFO (MainThread) [custom_components.ha_link2home.udpapi] send packet: a104e8fdf8052cce0009001102D271500101FF to 192.168.181.119
2024-07-29 15:35:05.900 DEBUG (MainThread) [custom_components.ha_link2home.coordinator] _async_update_data: started
2024-07-29 15:35:05.900 DEBUG (MainThread) [custom_components.ha_link2home.coordinator] Finished fetching ha_link2home data in 0.000 seconds (success: True)
```

**Comment by ReneNulschDE** [comment]
Could you share the output of the startup too? would like to check if there is a problem with the setup of the udp-server.

The socket goes on and stays on, right? What model do you have?

**Comment by ReneNulschDE** [comment]
Yesterday evening, I had the same problem with my outdoor socket. Let me try to reproduce this.

**Comment by ReneNulschDE** [comment]
Fixed with version v0.2.0, please update and report back if this is working for you.

**Comment by fsedarkalex** [comment]
After a few days of testing, I can say it got a little better (it rarely works) but in most cases the state does still not update.
